version: '3'

services:
  db:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${TTRSS_DB_USER}
      - POSTGRES_PASSWORD=${TTRSS_DB_PASS}
      - POSTGRES_DB=${TTRSS_DB_NAME}
      - TTRSS_AUTH_OIDC_NAME=${TTRSS_AUTH_OIDC_NAME}
      - TTRSS_AUTH_OIDC_URL=${TTRSS_AUTH_OIDC_URL}
      - TTRSS_AUTH_OIDC_CLIENT_ID=${TTRSS_AUTH_OIDC_CLIENT_ID}
      - TTRSS_AUTH_OIDC_CLIENT_SECRET=${TTRSS_AUTH_OIDC_CLIENT_SECRET}
      - TTRSS_AUTH_OIDC_VALIDATE_INTERVAL=${TTRSS_AUTH_OIDC_VALIDATE_INTERVAL}
    volumes:
      - db:/var/lib/postgresql/data

  app:
    image: cthulhoo/ttrss-fpm-pgsql-static:latest
    restart: unless-stopped
    volumes:
      - app:/var/www/html
      - config:/opt/tt-rss/config.d:ro
    depends_on:
      - db
    environment:
      - TTRSS_DB_USER=${TTRSS_DB_USER}
      - TTRSS_DB_PASS=${TTRSS_DB_PASS}
      - TTRSS_DB_NAME=${TTRSS_DB_NAME}
      - TTRSS_AUTH_OIDC_NAME=${TTRSS_AUTH_OIDC_NAME}
      - TTRSS_AUTH_OIDC_URL=${TTRSS_AUTH_OIDC_URL}
      - TTRSS_AUTH_OIDC_CLIENT_ID=${TTRSS_AUTH_OIDC_CLIENT_ID}
      - TTRSS_AUTH_OIDC_CLIENT_SECRET=${TTRSS_AUTH_OIDC_CLIENT_SECRET}
      - TTRSS_AUTH_OIDC_VALIDATE_INTERVAL=${TTRSS_AUTH_OIDC_VALIDATE_INTERVAL}

  updater:
    image: cthulhoo/ttrss-fpm-pgsql-static:latest
    restart: unless-stopped
    volumes:
      - app:/var/www/html
      - config:/opt/tt-rss/config.d:ro
    depends_on:
      - app
    environment:
      - TTRSS_DB_USER=${TTRSS_DB_USER}
      - TTRSS_DB_PASS=${TTRSS_DB_PASS}
      - TTRSS_DB_NAME=${TTRSS_DB_NAME}
      - TTRSS_AUTH_OIDC_NAME=${TTRSS_AUTH_OIDC_NAME}
      - TTRSS_AUTH_OIDC_URL=${TTRSS_AUTH_OIDC_URL}
      - TTRSS_AUTH_OIDC_CLIENT_ID=${TTRSS_AUTH_OIDC_CLIENT_ID}
      - TTRSS_AUTH_OIDC_CLIENT_SECRET=${TTRSS_AUTH_OIDC_CLIENT_SECRET}
      - TTRSS_AUTH_OIDC_VALIDATE_INTERVAL=${TTRSS_AUTH_OIDC_VALIDATE_INTERVAL}
    command: /opt/tt-rss/updater.sh

  web-nginx:
    image: cthulhoo/ttrss-web-nginx:latest
    restart: unless-stopped
    environment:
      - TTRSS_DB_USER=${TTRSS_DB_USER}
      - TTRSS_DB_PASS=${TTRSS_DB_PASS}
      - TTRSS_DB_NAME=${TTRSS_DB_NAME}
      - TTRSS_AUTH_OIDC_NAME=${TTRSS_AUTH_OIDC_NAME}
      - TTRSS_AUTH_OIDC_URL=${TTRSS_AUTH_OIDC_URL}
      - TTRSS_AUTH_OIDC_CLIENT_ID=${TTRSS_AUTH_OIDC_CLIENT_ID}
      - TTRSS_AUTH_OIDC_CLIENT_SECRET=${TTRSS_AUTH_OIDC_CLIENT_SECRET}
      - TTRSS_AUTH_OIDC_VALIDATE_INTERVAL=${TTRSS_AUTH_OIDC_VALIDATE_INTERVAL}
    ports:
      - 8281:80
    volumes:
      - app:/var/www/html
    depends_on:
      - app

volumes:
  config:
  db:
  app:
  backups:
