name: Integrate `autoupdate` branches using rebase
on:
  workflow_dispatch:
  workflow_run:
    workflows:
     - Deploy service, generate certificates, and update NGINX configuration
    types: 
      - completed

jobs:
  autoupdate:
    runs-on: ubuntu-latest
    steps:
      - id: automerge
        name: automerge
        uses: "pascalgn/automerge-action@v0.16.4"
        env:
          GITHUB_TOKEN: ${{ secrets.RENOVATE_TOKEN }}
          MERGE_LABELS: "autoupdate"
          MERGE_METHOD: "rebase"
          UPDATE_METHOD: "rebase"
          UPDATE_RETRIES : 10
          UPDATE_RETRY_SLEEP: 30
          LOG: "TRACE"  # or "DEBUG"
