name: Deploy service, generate certificates, and update NGINX configuration

on:
  push:
    branches: [ "main" ]

jobs:
  call-reusable:
    uses: mahn-ke/.github/.github/workflows/deploy.yml@main
    secrets: inherit
