name: Dependency updates

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

concurrency:
  group: renovate-${{ github.ref }}
  cancel-in-progress: true
    
jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
        
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v43.0.6
        with:
          token: ${{ secrets.RENOVATE_TOKEN }}
